name       : python-pyrate-limiter
version    : 2.10.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pyrate-limiter/pyrate_limiter-2.10.0.tar.gz : 98cc52cdbe058458e945ae87d4fd5a73186497ffa545ee6e98372f8599a5bd34
license    : MIT
homepage   : https://pyratelimiter.readthedocs.io/
component  : programming.python
summary    : Python rate limiter using Leaky-Bucket algorithm
description: |
    The request rate limiter using Leaky-Bucket algorithm
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
